// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPsG7i3DQNwCOjZr3D39hZWbhougq0Kyk',
    appId: '1:87797264263:web:6c1e612d99406341c6ad22',
    messagingSenderId: '87797264263',
    projectId: 'busbooking-efcaa',
    authDomain: 'busbooking-efcaa.firebaseapp.com',
    databaseURL: 'https://busbooking-efcaa-default-rtdb.firebaseio.com',
    storageBucket: 'busbooking-efcaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVeRHfPWg7p_p6eMvMIhFLr2f0HdqP9Qg',
    appId: '1:87797264263:android:741012bdfea67305c6ad22',
    messagingSenderId: '87797264263',
    projectId: 'busbooking-efcaa',
    databaseURL: 'https://busbooking-efcaa-default-rtdb.firebaseio.com',
    storageBucket: 'busbooking-efcaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdpDmht78PalTw09htBOADRpRBdY2ZmAg',
    appId: '1:87797264263:ios:49921a8cd979740ac6ad22',
    messagingSenderId: '87797264263',
    projectId: 'busbooking-efcaa',
    databaseURL: 'https://busbooking-efcaa-default-rtdb.firebaseio.com',
    storageBucket: 'busbooking-efcaa.firebasestorage.app',
    iosBundleId: 'com.example.busBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdpDmht78PalTw09htBOADRpRBdY2ZmAg',
    appId: '1:87797264263:ios:49921a8cd979740ac6ad22',
    messagingSenderId: '87797264263',
    projectId: 'busbooking-efcaa',
    databaseURL: 'https://busbooking-efcaa-default-rtdb.firebaseio.com',
    storageBucket: 'busbooking-efcaa.firebasestorage.app',
    iosBundleId: 'com.example.busBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPsG7i3DQNwCOjZr3D39hZWbhougq0Kyk',
    appId: '1:87797264263:web:c506c9bb1d897b0ac6ad22',
    messagingSenderId: '87797264263',
    projectId: 'busbooking-efcaa',
    authDomain: 'busbooking-efcaa.firebaseapp.com',
    databaseURL: 'https://busbooking-efcaa-default-rtdb.firebaseio.com',
    storageBucket: 'busbooking-efcaa.firebasestorage.app',
  );
}
